# Generated by Django 3.2.12 on 2022-03-13 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Event Name')),
                ('location', models.TextField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('seats', models.PositiveIntegerField(default=0, verbose_name='Seats')),
                ('ticket_amount', models.FloatField(default=0, verbose_name='Ticket Amount')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_quantity', models.PositiveIntegerField(default=0, verbose_name='Ticket Quantity')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Total Price')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Id')),
            ],
            options={
                'db_table': 'event_booking_cart',
            },
        ),
    ]
