# Generated by Django 3.2.12 on 2022-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220313_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location'),
        ),
    ]
